---
abstract: 'Search and manage eBay auctions'
author:
  - 'Martin Thurn, C<mthurn@cpan.org>, L<http://www.sandcrawler.com/SWB/cpan-modules.html>.'
build_requires:
  Bit::Vector: 0
  Data::Dumper: 0
  Date::Manip: 0
  IO::Capture::Stderr: 0
  Test::More: 0
  WWW::Search::Test: 2.265
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: WWW::Ebay
name: WWW-Ebay
no_index:
  directory:
    - inc
    - t
recommends:
  Tk: 800
requires:
  Bit::Vector: 0
  Carp: 0
  Crypt::SSLeay: 0
  Data::Dumper: 0
  Date::Manip: 0
  File::Glob: 0
  File::Spec: 0
  HTML::Form: 0
  HTML::Parser: 3
  HTML::TreeBuilder: 0
  HTTP::Cookies: 0
  HTTP::Request::Common: 0
  LWP::Simple: 0
  LWP::UserAgent: 0
  URI: 0
  WWW::Search: 2.525
  WWW::Search::Ebay: 2.231
  WWW::SearchResult: 2.07
resources:
  license: http://dev.perl.org/licenses/
version: 0.087
