--- 
abstract: Search and manage eBay auctions
author: 
  - Martin Thurn <mthurn@cpan.org>
build_requires: 
  Bit::Vector: 0
  Data::Dumper: 0
  Date::Manip: 0
  IO::Capture::Stderr: 0
  Test::Inline: 0
  Test::More: 0
  WWW::Search::Test: 2.265
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: WWW-Ebay
no_index: 
  directory: 
    - inc
    - t
recommends: 
  Tk: 800
requires: 
  Bit::Vector: 0
  Carp: 0
  Crypt::SSLeay: 0
  Data::Dumper: 0
  Date::Manip: 0
  File::Glob: 0
  File::Spec: 0
  HTML::Form: 0
  HTML::Parser: 3
  HTML::TreeBuilder: 0
  HTTP::Cookies: 0
  HTTP::Request::Common: 0
  LWP::Simple: 0
  LWP::UserAgent: 0
  URI: 0
  WWW::Search: 2.525
  WWW::Search::Ebay: 2.181
  WWW::SearchResult: 2.07
version: 0.083
